2023-01-01 14:48:15,880 (ffffb6d84890) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 629d580 (Thu Dec 08 08:49:09 UTC 2022)
2023-01-01 14:48:15,881 (ffffb6d84890) :  DEBUG (core:361) - Using the elevated policy
2023-01-01 14:48:15,882 (ffffb6d84890) :  DEBUG (core:450) - Starting runtime component.
2023-01-01 14:48:15,885 (ffffb6d84890) :  DEBUG (core:450) - Starting caching component.
2023-01-01 14:48:15,886 (ffffb6d84890) :  DEBUG (core:450) - Starting data component.
2023-01-01 14:48:15,886 (ffffb6d84890) :  DEBUG (core:450) - Starting networking component.
2023-01-01 14:48:15,887 (ffffb6d84890) :  DEBUG (networking:265) - No cookie jar found
2023-01-01 14:48:15,897 (ffffb6d84890) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2023-01-01 14:48:15,898 (ffffb6d84890) :  DEBUG (core:450) - Starting localization component.
2023-01-01 14:48:15,899 (ffffb6d84890) :  INFO (localization:409) - Setting the default locale to en-us
2023-01-01 14:48:15,899 (ffffb6d84890) :  DEBUG (core:450) - Starting messaging component.
2023-01-01 14:48:15,900 (ffffb6d84890) :  DEBUG (core:450) - Starting debugging component.
2023-01-01 14:48:15,901 (ffffb6d84890) :  DEBUG (core:450) - Starting services component.
2023-01-01 14:48:15,902 (ffffb6d84890) :  DEBUG (core:450) - Starting myplex component.
2023-01-01 14:48:15,903 (ffffb6d84890) :  DEBUG (core:450) - Starting notifications component.
2023-01-01 14:48:15,904 (ffffb3aaab08) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2023-01-01 14:48:15,955 (ffffb6d84890) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2023-01-01 14:48:15,962 (ffffb6d84890) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-01-01 14:48:15,969 (ffffb6d84890) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-01-01 14:48:15,970 (ffffb6d84890) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 242, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 220, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2023-01-01 14:48:15,974 (ffffb3865b08) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2023-01-01 14:48:15,974 (ffffb6d84890) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2023-01-01 14:48:15,976 (ffffb6d84890) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2023-01-01 14:48:15,978 (ffffb3865b08) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2023-01-01 14:48:15,980 (ffffb3818b08) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2023-01-01 14:48:15,983 (ffffb6d84890) :  DEBUG (core:150) - Finished starting framework core
2023-01-01 14:48:15,984 (ffffb6d84890) :  DEBUG (core:560) - Loading plug-in code
2023-01-01 14:48:15,987 (ffffb3818b08) :  DEBUG (core:538) - Machine identifier is 0f00f9916b10d7dcfc749828c4348900652222fa
2023-01-01 14:48:16,005 (ffffb3818b08) :  DEBUG (core:539) - Server version is 1.30.0.6486-629d58034
2023-01-01 14:48:16,006 (ffffb3865b08) :  DEBUG (services:362) - Loaded services
2023-01-01 14:48:16,012 (ffffb383bb08) :  DEBUG (services:438) - No shared code to load
2023-01-01 14:48:16,139 (ffffb6d84890) :  DEBUG (core:566) - Finished loading plug-in code
2023-01-01 14:48:16,141 (ffffb6d84890) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2023-01-01 14:48:16,142 (ffffb6d84890) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2023-01-01 14:48:16,147 (ffffb6d84890) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2023-01-01 14:48:35,561 (ffffb6d84890) :  INFO (core:611) - Started plug-in
2023-01-01 14:48:35,564 (ffffb6d84890) :  DEBUG (socketinterface:160) - Starting socket server
2023-01-01 14:48:35,567 (ffffb6d84890) :  DEBUG (runtime:1117) - Created a thread named 'start'
2023-01-01 14:48:35,568 (ffffb6d84890) :  INFO (socketinterface:184) - Socket server started on port 34049
2023-01-01 14:48:35,570 (ffffb6d84890) :  INFO (pipeinterface:25) - Entering run loop
2023-01-01 14:48:35,571 (ffffb6d84890) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2023-01-01 14:48:35,574 (ffffb6d84890) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2023-01-01 14:48:35,576 (ffffb6d84890) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2023-01-01 14:48:35,584 (ffffb2d7fb08) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 14:48:35,586 (ffffb2d5cb08) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 14:48:35,597 (ffffb2d7fb08) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-01 14:48:35,605 (ffffb2d39b08) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 14:48:35,613 (ffffb2d7fb08) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 14:48:35,613 (ffffb2d5cb08) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-01 14:48:35,620 (ffffb2d5cb08) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 14:48:35,622 (ffffb2d5cb08) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-01 14:48:35,623 (ffffb2d5cb08) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2023-01-01 14:48:35,621 (ffffb2d39b08) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-01 14:48:35,618 (ffffb2d7fb08) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-01 14:48:35,628 (ffffb2d7fb08) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2023-01-01 14:48:35,627 (ffffb2d39b08) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-01 14:48:35,631 (ffffb2d39b08) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-01 14:48:35,632 (ffffb2d39b08) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
